language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24

before_install:
		- chmod +x gradlew

script:
   - ./gradlew clean assemble
